### ISSUE TITLE
Credential File format

### ISSUE THREAD

**Issue by Voidi** [oGGy990/certbot-dns-inwx#10]
What is the format to store inwx login credentials in the file?

**Comment by oGGy990** [comment]
Oh, I see, setuptools don't install the additional files.
It's like this file in the repository: [inwx.cfg](https://github.com/oGGy990/certbot-dns-inwx/blob/master/inwx.cfg) Just copy it to /etc/letsencrypt/inwx.cfg or supply another path on the command line.
