### ISSUE TITLE
Release on pypi.org 

### ISSUE THREAD

**Issue by slauger** [oGGy990/certbot-dns-inwx#11]
Hi @oGGy990,

hope your doing fine. ;)

Thanks for your work here. I created an RPM package for the plugin for EL machines. Things would be easier if your repository would have some version tags. Could you add tags and maybe also release this on pypi.org?

Cheers, Simon

**Comment by oGGy990** [comment]
Hey @slauger,

I'm doing fine, hope you do too. :-)

I've added a tag for v2.1.0 (before PyPI) and a tag for v2.1.1 (now also on [PyPI](https://pypi.org/project/certbot-dns-inwx/)).
The README and setup.py are updated accordingly.
