### ISSUE TITLE
Release for arm64 architecture

### ISSUE THREAD

**Issue by lcnittl** [oGGy990/certbot-dns-inwx#20]
Trying to install via snap on a raspberry Pi gives the following:

```
root@host ~# snap install certbot-dns-inwx
error: snap "certbot-dns-inwx" is not available on stable for this architecture
       (arm64) but exists on other architectures (amd64).
```

Would it be possible to also release this plugin for `arm64` arch?

**Comment by lcnittl** [comment]
Looks like this requires

```yaml
architectures:
  - build-on: amd64
    run-on: armhf
```

to be added to `snapcraft.yaml` like [here](https://github.com/ogra1/pi-kiosk-gadget/blob/90692a18ad8400c9e7fdd331d3d203003a8dbd7a/snap/snapcraft.yaml#L11-L13).

Cf also https://forum.snapcraft.io/t/how-to-enable-arm64-builds/5618 and https://forum.snapcraft.io/t/architectures/4972 .

Would be awesome! Thx :-)

**Comment by oGGy990** [comment]
Hey @lcnittl,

I added the project to the snapcraft CI build system and adjusted the `snapcraft.yaml`.

You should be able to install it using `sudo snap install --channel=edge certbot-dns-inwx`.
If it works (or not), please give some feedback. I'll add it to the stable channel then.

**Comment by lcnittl** [comment]
Thanks a lot! It is working for me as expected.

You may close this issue.

**Comment by oGGy990** [comment]
Great! You may switch to the stable channel using `sudo snap refresh --channel=stable certbot-dns-inwx` now.
