### ISSUE TITLE
unable to modify domains that only exist in inwx Nameserver settings, but not in domain list

### ISSUE THREAD

**Issue by Catscrash** [oGGy990/certbot-dns-inwx#22]
Hi,

I have a domain mail.example.com.

Example.com is not owned by me, but mail.example.com settings have NS settings to inwx Nameservers and I have added the Domain to my inwx Account at the Nameserver settings.

I can now modify the nameserver settings in inwx properly, but the inwx certbot plugin says:

Encountered exception during recovery: certbot.errors.PluginError: Unable to determine base domain for _acme-challenge.mail.example.com using names: ['_acme-challenge.mail.example.com', 'mail.example.com', 'example.com', 'com'].
Unable to determine base domain for _acme-challenge.mail.example.com using names: ['_acme-challenge.mail.example.com', 'mail.example.com', 'example.com', 'com'].

Is this something that can be worked around, or do I have to accept that the plugin only can manage domains that are actually owned by this account?

thanks

**Comment by oGGy990** [comment]
Hi Catscrash,
this is pretty much linked to the open PR #21. I'm not 100% sure about merging this or changing the behavior as it is only required if violating the statement on INWX' nameserver configuration page: 

> We do not allow the usage of external domains in our nameservers.

So yes, most likely it can be worked around by using the version of @nilsding.

On the other hand, I have violated this myself already during the process of transferring some domains from another registrar...

**Comment by Catscrash** [comment]
oh, I did not know that it's not allowed, I never actually read that text... :-/ . Thank you for that info, I will use the cname following method instead.

**Comment by acydburn** [comment]
Hi,

@oGGy990  Actually this is allowed and possible (now) with a Nameserver package for external domains you need to buy. As far as i know you need to write the support to buy one of those (i did so yesterday). 

I think it is a good thing to not allow this out-of-the-box, but maybe behind a switch? 

Best
