### ISSUE TITLE
Using dns-inwx-follow-cnames with snap installation

### ISSUE THREAD

**Issue by Catscrash** [oGGy990/certbot-dns-inwx#23]
Hi,

I installed the inwx plugin and certbot using snap. Now I'm trying to get dns-inwx-follow-cnames to work. I installed 

apt install python3-dnspython

but the option doesn't appear. Do I have to do anything to snap to recognize the package and offer me dns-inwx-follow-cnames as option?

thanks

**Comment by oGGy990** [comment]
Hi Catscrash,

the snap is built without dnspython integrated. There is also no way to add it later on, so the following of CNAMEs is not available within the snap installation.

**Comment by Catscrash** [comment]
ok, thank you. I did a reinstall without snap, that works
