### ISSUE TITLE
Don't set dns_inwx_shared_secret when not needed

### ISSUE THREAD

**Issue by leegarrett** [oGGy990/certbot-dns-inwx#29]
Currently, when 2FA is disabled, you still have to set `dns_inwx_shared_secret = your_shared_secret optional` in the config. Otherwise the plugin throws a python exception.

I think it would be much better UX if you can leave it out when you don't have 2FA enabled.

**Comment by oGGy990** [comment]
While I totally agree, the certbot credentials file API does not support optional fields unfortunately - even now at v3.0.0.

I could only work-around this by using the normal configuration file API instead. But I'm not really convinced by that.

So currently, "wontfix", sorry.
