### ISSUE TITLE
PluginError: Unable to determine base domain for _acme-challenge....

### ISSUE THREAD

**Issue by Wachert** [oGGy990/certbot-dns-inwx#33]
Requesting a certificate for a.b.c and *.a.b.c
Encountered exception during recovery: certbot.errors.PluginError: Unable to determine base domain for _acme-challenge.a.b.c using names: ['_acme-challenge.a.b.c', 'a.b.c', 'b.c', 'c'].
Unable to determine base domain for _acme-challenge.a.b.c using names: ['_acme-challenge.a.b.c', 'a.b.c', 'b.c', 'c'].

Certbot and the plugin installed using snap, version 2.8.0

The INWX User is an additional User using the Nameserver Role.

**Comment by Wachert** [comment]
OK solved... the user needs more rights...

**Comment by Wachert** [comment]
ok solved, the inwx user needs more rights

**Comment by CrookedBIOS** [comment]
I had the same issue and indeed had to give my additional INWX user the 'Domain Management' role instead of only the 'DNS Management' role.
