### ISSUE TITLE
Plugin seems to ignore config-dir setting

### ISSUE THREAD

**Issue by wowcut** [oGGy990/certbot-dns-inwx#7]
This plugin seems to ignore the `config-dir` setting.

**Comment by oGGy990** [comment]
The option to set the INWX credentials file is:
`--certbot-dns-inwx:dns-inwx-credentials=/your/path/to/the/file`

Just like the builtin DNS plugins, but with the required prefix

**Comment by wowcut** [comment]
Ah, ok, thank you!
